### PR TITLE
Use tag_invoke for value_to & value_from

### PR DESCRIPTION
**Pull request by sdkrystian**

### CODE REVIEW

**Comment by sdkrystian** [comment]
@pdimov (can't request you for review so I have to tag you)

**Comment by vinniefalco** [comment]
This needs tests and coverage before being reviewed

**Comment by sdarwin** [comment]
Hey @sdkrystian ,

Documentation previews aren't building. It looks like test/snippets.cpp should be modified:

```
//[snippet_exchange_5
// VFALCO TODO
```

change to:

```
//[snippet_exchange_5
// VFALCO TODO
//]
```

**Comment by sdkrystian** [comment]
@sdarwin Good catch, thanks!

**Pull request closed without merging**
