### PR TITLE
Fix integer benchmark ranges

### PR DESCRIPTION
**Pull request by sdkrystian**
`integers-32` contains numbers in the range `-2^32 to 2^32 - 1` and `integers-64` contains numbers in the range `-2^64 to 2^64 - 1` that don't fall within the range of `integers-32`. Numbers are generated randomly based on length, so it's a good mix of short and long numbers.

### CODE REVIEW

**Comment by sdkrystian** [comment]
Updated to include `-2^32 to 2^32 - 1` in `integers-64`

**Comment by sdkrystian** [comment]
Whoops, accidently deleted the branch when pruning stale branches.

**Comment by vinniefalco** [comment]
Is this relevant now that we are using an updated set of benchmark files?

**Comment by sdkrystian** [comment]
Nope, this can be closed.

**Pull request closed without merging**
