### PR TITLE
benchmarked libraries are not submodules

### LINKED ISSUE #70: Don't use submodules
bench should get nlohmann and rapidjson from a script not as a submodule

### PR DESCRIPTION
**Pull request by sdkrystian**
fix #70

### CODE REVIEW

**Comment by vinniefalco** [comment]
What, you don't want to ship copies of RapidJSON and nlohmann's JSON with Boost?

**Comment by sdkrystian** [comment]
LOL

**Comment by sdkrystian** [comment]
@vinniefalco Should we add `/bench/lib` to the gitignore?

**Comment by vinniefalco** [comment]
Yeah we should add it to gitignore if running the script would change the working set

**Comment by vinniefalco** [comment]
I added it to .gitignore

**Pull request closed without merging**
