### PR TITLE
test pr benchmarks

### PR DESCRIPTION
**Pull request by sdarwin**
Don't merge.
Testing the functionality of benchmark computation on pull requests. Processing takes an hour or so.

### CODE REVIEW

**Comment by sdarwin** [comment]
Looks good. Closing PR.

**Comment by vinniefalco** [comment]
I thought the image would be inlined in the message

**Comment by sdarwin** [comment]
> I thought the image would be inlined in the message

I will what can be done about showing the images in a smaller window... Re-opening the issue.

**Comment by sdkrystian** [comment]
Hm, the wild variance in the results might be my fault. For gcc it might be comparing against clang develop.... I'll check

**Comment by sdarwin** [comment]
> Hm, the wild variance

I was also surprised by that.  But it wasn't an exact comparison because the develop branch changed since the pull request was submitted.   Further testing of the same commit with itself shows less variance.

**Comment by vinniefalco** [comment]
is this pull request actionable?

**Comment by sdarwin** [comment]
> is this pull request actionable?

It has become actionable, because it seems the build job is occasionally triggering for no reason.  The benchmarks ran, however there wasn't a new commit.  Investigating...

**Comment by sdarwin** [comment]
Latest theory:  Although no new commits have been submitted to the PR, the "target" or "base" of the PR (which is the develop branch) has changed in the meantime, and that is causing the plugin to sometimes trigger rebuilds. 

@sdkrystian  -  benchmark computations have been revised to compare against the point of divergence from the develop branch instead of the newest commit.

**Pull request closed without merging**
